Update Miniforge blog post
BiAPoL/blog pull request #79
Opened 2024-07-08 10:05 UTC by marabuuu

Hi @stefanhahmann,

I updated the Miniforge blogpost again and it would be super cool if you could have a look at it. 
I had a chat with Robert and there I found out that we don't need to write `mamba ...` anymore, but can simply use `conda ...`. 

And now, I was trying to find out if I can also remove the `-c conda-forge` from all commands and it seems to be ok, because according to the [conda-forge documentation](https://conda-forge.org/docs/user/introduction/), conda-forge is the default channel of Miniforge.

I feel that these two changes make the installation instructions a bit easier to follow for python beginners, but I am always happy about your input and let me know if you want to have anything changed.

Best,
Mara

2024-07-18 09:03 UTC, stefanhahmann requested changes
Hi @marabuuu,

when I saw your PR, I thought that it would not be a good idea to exchange `mamba` with `conda`, since `mamba` used to be much more efficient than `conda` in solving environments.
However, this does not seem to be the case anymore, at least not with miniforge3, and I was not aware of this.
I just made a test on an independent machine where I freshly installed miniforge3.

I tested 

`conda create -n speed-test-conda devbio-napari python=3.9 pyqt`

vs

`mamba create -n speed-test-mamba devbio-napari python=3.9 pyqt -c conda-forge`

and the environments were created in about the same time (~5 minutes on the machine+network where I tested).

Thus, I agree, since conda may be more well known, it is good idea to replace `mamba` with `conda` in the blog post.

However, I think with your changes, there are still some references to Mamba, which may make it confusing for readers. Some places, where I spotted this:

- One could think about renaming the link of the blog post by renaming the folder in github (and replace mambaforge by miniforge in it): https://biapol.github.io/blog/mara_lampert/getting_started_with_mambaforge_and_python
  - In this case the link to this blog post in this older blog post would need to be replaced: https://biapol.github.io/blog/johannes_mueller/anaconda_getting_started/Readme.html
- The section "Using Mamba" could be renamed to "Using Conda". There are some more mention(s) for "Mamba" in this section, which could be replaced.
  - Please do also check other sections of the blog post for mentions of "Mamba". To avoid confusion I would replace them all by "Conda"

2024-07-18 12:33 UTC, stefanhahmann commented
> I updated the Miniforge blogpost again and it would be super cool if you could have a look at it.

Hi @marabuuu I do not see any changes newer than July 8th (cf. https://github.com/BiAPoL/blog/pull/79/commits). Can you check, if you committed and pushed your latest updates? 

You could also consider using `Commit suggestion` and/or `Resolve conversation` / `Reply` to indicate on which of the comments you have worked.

![grafik](https://github.com/user-attachments/assets/1524a2a7-f857-493a-931d-5a184612ad63)

2024-07-19 12:50 UTC, marabuuu commented on docs/mara_lampert/getting_started_with_mambaforge_and_python/readme.md
>  > **_Note:_** This is an update of a [previous Blogpost](https://biapol.github.io/blog/johannes_mueller/anaconda_getting_started/) written by Johannes.
true, thanks for spotting this!

2024-07-19 13:08 UTC, marabuuu commented on docs/mara_lampert/getting_started_with_mambaforge_and_python/readme.md
> +This blog post explains what Python and [Mamba](https://mamba.readthedocs.io/en/latest/) / Miniforge is, and how you can download and setup it on your computer. We will also go through some steps how
Makes sense, I will link Conda through https://docs.readthedocs.io/en/stable/guides/conda.html instead

2024-07-19 13:29 UTC, marabuuu commented
Hi @stefanhahmann,

Thank you for your input and changes! Very cool and helpful. I worked most of you recommendations in, the only thing where I have doubts is changing the link of the blog post:

> One could think about renaming the link of the blog post by renaming the folder in github (and replace mambaforge by miniforge in it): https://biapol.github.io/blog/mara_lampert/getting_started_with_mambaforge_and_python

Because if we change the link then we would need to update all the resources where we mentioned this blogpost and I think this installation blogpost was mentioned in several different resources, not only my own, but also for example Roberts and I would not have the overview in which of these resources I need to update the link.

Is there a way to update a link so that when someone clicks the old link, it automatically opens the new link instead?

Best,
Mara

2024-07-19 13:45 UTC, stefanhahmann commented
> Hi @stefanhahmann,
> 
> Thank you for your input and changes! Very cool and helpful. I worked most of you recommendations in, the only thing where I have doubts is changing the link of the blog post: 
> Because if we change the link then we would need to update all the resources where we mentioned this blogpost and I think this installation blogpost was mentioned in several different resources, not only my own, but also for example Roberts and I would not have the overview in which of these resources I need to update the link.

I agree. I had similar thoughts about this. It could even be that externals that we do not even know referenced this blog post and those links would break as well, which would be a pitty.

> Is there a way to update a link so that when someone clicks the old link, it automatically opens the new link instead?

I am not aware of options for link forwarding in the github blog system.

Perhaps, the cleanest solution would have been to actually write new blog post (like we did, to document the changes from anaconda to mambaforge) and reference the new blog post from the current one (like the mambaforge blog post was referenced from the anaconda blog post).

I leave it up to you to decide, if this would be worth the effort.

Best,
Stefan.

2024-07-19 13:46 UTC, stefanhahmann approved these changes

2024-07-24 09:34 UTC, closed without merging